/**
 * Lights Out — a grid of lights. Pressing a cell toggles it and its
 * orthogonal neighbours. Turn every light OFF to win.
 *
 * Puzzles are generated by starting from the all-off (solved) board and
 * applying a set of random presses, so every puzzle is guaranteed solvable —
 * pressing that same set of cells again is always a valid solution. Because
 * pressing a cell twice cancels out, we only ever press distinct cells, which
 * makes `par` (the number of presses used) an honest upper bound on the
 * minimum solution length.
 */

export const LEVELS = {
  Easy:   { size: 3, scramble: 3,  label: "3×3 · gentle warm-up" },
  Medium: { size: 4, scramble: 5,  label: "4×4 · balanced" },
  Hard:   { size: 5, scramble: 8,  label: "5×5 · classic" },
  Expert: { size: 6, scramble: 12, label: "6×6 · brain-burner" },
};

export function emptyGrid(n) {
  return Array.from({ length: n }, () => Array.from({ length: n }, () => false));
}

const NEIGHBOURS = [
  [0, 0],
  [1, 0],
  [-1, 0],
  [0, 1],
  [0, -1],
];

/** Return a new grid with (r,c) and its orthogonal neighbours toggled. */
export function pressAt(grid, r, c) {
  const n = grid.length;
  const next = grid.map((row) => row.slice());
  for (const [dr, dc] of NEIGHBOURS) {
    const nr = r + dr;
    const nc = c + dc;
    if (nr >= 0 && nr < n && nc >= 0 && nc < n) next[nr][nc] = !next[nr][nc];
  }
  return next;
}

export function isSolved(grid) {
  return grid.every((row) => row.every((cell) => !cell));
}

export function litCount(grid) {
  let n = 0;
  for (const row of grid) for (const cell of row) if (cell) n++;
  return n;
}

/**
 * Build a solvable puzzle for an n×n board using ~`presses` distinct toggles.
 * @returns {{ grid: boolean[][], par: number }}
 */
export function scramble(n, presses) {
  let grid = emptyGrid(n);
  const used = new Set();
  let par = 0;
  const target = Math.min(presses, n * n);
  let guard = 0;
  while (par < target && guard < target * 30) {
    guard++;
    const r = Math.floor(Math.random() * n);
    const c = Math.floor(Math.random() * n);
    const key = r * n + c;
    if (used.has(key)) continue; // pressing the same cell twice cancels out
    used.add(key);
    grid = pressAt(grid, r, c);
    par++;
  }
  // Never hand the player an already-solved board.
  if (isSolved(grid)) {
    grid = pressAt(grid, 0, 0);
    par = 1;
  }
  return { grid, par };
}

/**
 * Score a solved puzzle. Higher is better (feeds XP + achievements).
 * Full marks for solving in `par` moves or fewer, tapering as moves grow.
 */
export function scoreFor(size, par, moves) {
  const efficiency = Math.max(0, 1 - Math.max(0, moves - par) / (par * 2 || 1));
  return Math.round(size * 8 + efficiency * 40);
}

export function starsFor(par, moves) {
  if (moves <= par) return 3;
  if (moves <= Math.ceil(par * 1.6)) return 2;
  return 1;
}

const bestKey = (level) => `mm4_lights_best_${level}`;

/** Best = fewest moves to solve (lower is better); null if never solved. */
export function loadBest(level) {
  const v = Number(localStorage.getItem(bestKey(level)));
  return Number.isFinite(v) && v > 0 ? v : null;
}

export function saveBest(level, moves) {
  localStorage.setItem(bestKey(level), String(moves));
}
